### Cadastrar categoria
POST https://localhost:5001/api/categoria/create
Content-Type: application/json

{
  "categoriaId": 1,
  "nomecategoria": "bebida"
}



### Listar categoria
GET https://localhost:5001/api/categoria/list
